version: "3.7"

services:
  pocketbase:
    image: ghcr.io/muchweb/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv=PB_ENCRYPTION_KEY
    ports:
      - "8090:8090"
    environment:
      - PB_ENCRYPTION_KEY=change_this_to_a_random_32_char_secret
    volumes:
      - pocketbase_data:/pb_data

volumes:
  pocketbase_data:
