FROM ghcr.io/gis-ops/docker-valhalla/valhalla:latest

ENV tile_extract_url=https://download.geofabrik.de/north-america-latest.osm.pbf
ENV build_elevation=false
ENV build_admins=true
ENV build_time_zones=true
ENV force_rebuild=false

EXPOSE 8002
